//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heroes.Core.Castle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heroes.Core.Castle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap aa {
            get {
                object obj = ResourceManager.GetObject("aa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Angels {
            get {
                object obj = ResourceManager.GetObject("Angels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Archangels {
            get {
                object obj = ResourceManager.GetObject("Archangels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Archer {
            get {
                object obj = ResourceManager.GetObject("Archer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArcherTower {
            get {
                object obj = ResourceManager.GetObject("ArcherTower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArcherTower1 {
            get {
                object obj = ResourceManager.GetObject("ArcherTower1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap archerTowerArcher {
            get {
                object obj = ResourceManager.GetObject("archerTowerArcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArcherTowerDone {
            get {
                object obj = ResourceManager.GetObject("ArcherTowerDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArcherTowerUpg2 {
            get {
                object obj = ResourceManager.GetObject("ArcherTowerUpg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArmySelection {
            get {
                object obj = ResourceManager.GetObject("ArmySelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Barracks {
            get {
                object obj = ResourceManager.GetObject("Barracks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Barracks1 {
            get {
                object obj = ResourceManager.GetObject("Barracks1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BarracksDone {
            get {
                object obj = ResourceManager.GetObject("BarracksDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BarracksUpg2 {
            get {
                object obj = ResourceManager.GetObject("BarracksUpg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicCastle {
            get {
                object obj = ResourceManager.GetObject("BasicCastle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicTavern {
            get {
                object obj = ResourceManager.GetObject("BasicTavern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bh {
            get {
                object obj = ResourceManager.GetObject("bh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blacksmith {
            get {
                object obj = ResourceManager.GetObject("Blacksmith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blacksmith1 {
            get {
                object obj = ResourceManager.GetObject("Blacksmith1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blacksmith11 {
            get {
                object obj = ResourceManager.GetObject("Blacksmith11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlacksmithDone {
            get {
                object obj = ResourceManager.GetObject("BlacksmithDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrotherhoodDone {
            get {
                object obj = ResourceManager.GetObject("BrotherhoodDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrotherhoodDone1 {
            get {
                object obj = ResourceManager.GetObject("BrotherhoodDone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuildNewShip1 {
            get {
                object obj = ResourceManager.GetObject("BuildNewShip1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buy {
            get {
                object obj = ResourceManager.GetObject("buy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buyArcher {
            get {
                object obj = ResourceManager.GetObject("buyArcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buyArmy {
            get {
                object obj = ResourceManager.GetObject("buyArmy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buyArmy1 {
            get {
                object obj = ResourceManager.GetObject("buyArmy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buyGriffin {
            get {
                object obj = ResourceManager.GetObject("buyGriffin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buypikemem2 {
            get {
                object obj = ResourceManager.GetObject("buypikemem2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buySpellBook {
            get {
                object obj = ResourceManager.GetObject("buySpellBook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buySwordsmen {
            get {
                object obj = ResourceManager.GetObject("buySwordsmen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CapitalDone {
            get {
                object obj = ResourceManager.GetObject("CapitalDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capitall {
            get {
                object obj = ResourceManager.GetObject("Capitall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CapitalOut {
            get {
                object obj = ResourceManager.GetObject("CapitalOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap castle {
            get {
                object obj = ResourceManager.GetObject("castle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap castlebelowbar {
            get {
                object obj = ResourceManager.GetObject("castlebelowbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CastleBlock {
            get {
                object obj = ResourceManager.GetObject("CastleBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CastleDone {
            get {
                object obj = ResourceManager.GetObject("CastleDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CastleHall {
            get {
                object obj = ResourceManager.GetObject("CastleHall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Castlel {
            get {
                object obj = ResourceManager.GetObject("Castlel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap castleLow {
            get {
                object obj = ResourceManager.GetObject("castleLow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CastleOut {
            get {
                object obj = ResourceManager.GetObject("CastleOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cavalier {
            get {
                object obj = ResourceManager.GetObject("Cavalier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Champions {
            get {
                object obj = ResourceManager.GetObject("Champions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Citadel {
            get {
                object obj = ResourceManager.GetObject("Citadel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Citadel1 {
            get {
                object obj = ResourceManager.GetObject("Citadel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CityHall {
            get {
                object obj = ResourceManager.GetObject("CityHall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CityHallOut {
            get {
                object obj = ResourceManager.GetObject("CityHallOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close1 {
            get {
                object obj = ResourceManager.GetObject("close1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap confirm {
            get {
                object obj = ResourceManager.GetObject("confirm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crusaders {
            get {
                object obj = ResourceManager.GetObject("Crusaders", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap done {
            get {
                object obj = ResourceManager.GetObject("done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fort {
            get {
                object obj = ResourceManager.GetObject("Fort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Griffin {
            get {
                object obj = ResourceManager.GetObject("Griffin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GriffinBastion {
            get {
                object obj = ResourceManager.GetObject("GriffinBastion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GriffinBastion1 {
            get {
                object obj = ResourceManager.GetObject("GriffinBastion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GriffinBastionDone {
            get {
                object obj = ResourceManager.GetObject("GriffinBastionDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GriffinGriffinTower {
            get {
                object obj = ResourceManager.GetObject("GriffinGriffinTower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GriffinTower {
            get {
                object obj = ResourceManager.GetObject("GriffinTower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GriffinTower1 {
            get {
                object obj = ResourceManager.GetObject("GriffinTower1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GriffinTowerDone {
            get {
                object obj = ResourceManager.GetObject("GriffinTowerDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GriffinTowerUpg2 {
            get {
                object obj = ResourceManager.GetObject("GriffinTowerUpg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTMNUBAK {
            get {
                object obj = ResourceManager.GetObject("GTMNUBAK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTMNUBAK1 {
            get {
                object obj = ResourceManager.GetObject("GTMNUBAK1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuardHouse {
            get {
                object obj = ResourceManager.GetObject("GuardHouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuardhouseDone {
            get {
                object obj = ResourceManager.GetObject("GuardhouseDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guardhousePikemen {
            get {
                object obj = ResourceManager.GetObject("guardhousePikemen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GuardhouseUpg2 {
            get {
                object obj = ResourceManager.GetObject("GuardhouseUpg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halberdiers {
            get {
                object obj = ResourceManager.GetObject("Halberdiers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lighthouse {
            get {
                object obj = ResourceManager.GetObject("Lighthouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lighthouse22 {
            get {
                object obj = ResourceManager.GetObject("lighthouse22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LighthouseDone {
            get {
                object obj = ResourceManager.GetObject("LighthouseDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mage2 {
            get {
                object obj = ResourceManager.GetObject("Mage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mage3 {
            get {
                object obj = ResourceManager.GetObject("Mage3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mage4 {
            get {
                object obj = ResourceManager.GetObject("Mage4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MageGuildLevel1 {
            get {
                object obj = ResourceManager.GetObject("MageGuildLevel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MageGuildLevel11 {
            get {
                object obj = ResourceManager.GetObject("MageGuildLevel11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MageGuildLevel12 {
            get {
                object obj = ResourceManager.GetObject("MageGuildLevel12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MageGuildLevel13 {
            get {
                object obj = ResourceManager.GetObject("MageGuildLevel13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MageGuildLevel14 {
            get {
                object obj = ResourceManager.GetObject("MageGuildLevel14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MageGuildLevel4Done {
            get {
                object obj = ResourceManager.GetObject("MageGuildLevel4Done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marketplace {
            get {
                object obj = ResourceManager.GetObject("Marketplace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marketplace1 {
            get {
                object obj = ResourceManager.GetObject("Marketplace1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marksmen {
            get {
                object obj = ResourceManager.GetObject("Marksmen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Monastery {
            get {
                object obj = ResourceManager.GetObject("Monastery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Monastery2 {
            get {
                object obj = ResourceManager.GetObject("Monastery2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MonasteryDone {
            get {
                object obj = ResourceManager.GetObject("MonasteryDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MonasteryMonk {
            get {
                object obj = ResourceManager.GetObject("MonasteryMonk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MonasteryTown {
            get {
                object obj = ResourceManager.GetObject("MonasteryTown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Monks {
            get {
                object obj = ResourceManager.GetObject("Monks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pikemen {
            get {
                object obj = ResourceManager.GetObject("pikemen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pipipike {
            get {
                object obj = ResourceManager.GetObject("pipipike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PortalOfGlory {
            get {
                object obj = ResourceManager.GetObject("PortalOfGlory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PortalofGloryAngels {
            get {
                object obj = ResourceManager.GetObject("PortalofGloryAngels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PortalofGloryDone {
            get {
                object obj = ResourceManager.GetObject("PortalofGloryDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PortalOfGloryTown {
            get {
                object obj = ResourceManager.GetObject("PortalOfGloryTown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PortalofGloryUpg2 {
            get {
                object obj = ResourceManager.GetObject("PortalofGloryUpg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap purchase1 {
            get {
                object obj = ResourceManager.GetObject("purchase1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ResourceSilo {
            get {
                object obj = ResourceManager.GetObject("ResourceSilo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ResourceSiloDone {
            get {
                object obj = ResourceManager.GetObject("ResourceSiloDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoyalGriffins {
            get {
                object obj = ResourceManager.GetObject("RoyalGriffins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ship {
            get {
                object obj = ResourceManager.GetObject("Ship", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShipNoRiver {
            get {
                object obj = ResourceManager.GetObject("ShipNoRiver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shipyard {
            get {
                object obj = ResourceManager.GetObject("Shipyard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shipyard1 {
            get {
                object obj = ResourceManager.GetObject("Shipyard1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShipyardNoRiver {
            get {
                object obj = ResourceManager.GetObject("ShipyardNoRiver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Silo {
            get {
                object obj = ResourceManager.GetObject("Silo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap split {
            get {
                object obj = ResourceManager.GetObject("split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap split1 {
            get {
                object obj = ResourceManager.GetObject("split1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitArmy {
            get {
                object obj = ResourceManager.GetObject("splitArmy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stable {
            get {
                object obj = ResourceManager.GetObject("Stable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StableDone {
            get {
                object obj = ResourceManager.GetObject("StableDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stables {
            get {
                object obj = ResourceManager.GetObject("Stables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Swordsmen {
            get {
                object obj = ResourceManager.GetObject("Swordsmen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SwordsmenBarrack {
            get {
                object obj = ResourceManager.GetObject("SwordsmenBarrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tavern {
            get {
                object obj = ResourceManager.GetObject("Tavern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tavern1 {
            get {
                object obj = ResourceManager.GetObject("Tavern1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TBcsback {
            get {
                object obj = ResourceManager.GetObject("TBcsback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TBCsM301 {
            get {
                object obj = ResourceManager.GetObject("TBCsM301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TBCsM401 {
            get {
                object obj = ResourceManager.GetObject("TBCsM401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TBCsMag2 {
            get {
                object obj = ResourceManager.GetObject("TBCsMag2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TownHall {
            get {
                object obj = ResourceManager.GetObject("TownHall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TownHall1 {
            get {
                object obj = ResourceManager.GetObject("TownHall1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TownScrn {
            get {
                object obj = ResourceManager.GetObject("TownScrn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrainingGround {
            get {
                object obj = ResourceManager.GetObject("TrainingGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrainingGroundCavaliers {
            get {
                object obj = ResourceManager.GetObject("TrainingGroundCavaliers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TraininggroundDone {
            get {
                object obj = ResourceManager.GetObject("TraininggroundDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrainingGrounds {
            get {
                object obj = ResourceManager.GetObject("TrainingGrounds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrainingGroundUpg2 {
            get {
                object obj = ResourceManager.GetObject("TrainingGroundUpg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpgArcherTower {
            get {
                object obj = ResourceManager.GetObject("UpgArcherTower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpgBarracks {
            get {
                object obj = ResourceManager.GetObject("UpgBarracks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpgGriffinTower {
            get {
                object obj = ResourceManager.GetObject("UpgGriffinTower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpgGuardhouse {
            get {
                object obj = ResourceManager.GetObject("UpgGuardhouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpgMonastery {
            get {
                object obj = ResourceManager.GetObject("UpgMonastery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpgMonasteryTown {
            get {
                object obj = ResourceManager.GetObject("UpgMonasteryTown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpgPortalofGlory {
            get {
                object obj = ResourceManager.GetObject("UpgPortalofGlory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpgTrainingGrounds {
            get {
                object obj = ResourceManager.GetObject("UpgTrainingGrounds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VillageHall {
            get {
                object obj = ResourceManager.GetObject("VillageHall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zealots {
            get {
                object obj = ResourceManager.GetObject("Zealots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
